const ErrorCode = {
  TOPIC_ALREADY_EXISTS: 'TOPIC_ALREADY_EXISTS',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  TOPIC_NAME_ERROR: 'TOPIC_NAME_ERROR',
  RESOURCE_NAME_ERROR: 'RESOURCE_NAME_ERROR',
};

export default ErrorCode;
