name: Build Client

on:
  push:
    branches:
      - 'master'
    paths:
      - 'src/client/**'
  pull_request:
    branches:
      - '*'
    paths:
      - 'src/client/**'

env:
  CLIENT_PATH: 'src/client'

jobs:
  build:
    name: Build
    runs-on: macos-10.15
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Setup Node'
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: 'Install packages'
        run: 'npm ci'
        working-directory: ${{ env.CLIENT_PATH }}

      # - name: 'Lint'
      #   run: 'npm run lint'
      #   working-directory: ${{ env.CLIENT_PATH }}

      # - name: 'Test'
      #   run: 'npm run test:ci'
      #   working-directory: ${{ env.CLIENT_PATH }}

      - name: 'Install E2E Browsers'
        run: 'PLAYWRIGHT_BROWSERS_PATH=/Users/runner/work/playwright npm install playwright-chromium@1.14.0'

      - name: 'E2E'
        run: 'PLAYWRIGHT_BROWSERS_PATH=/Users/runner/work/playwright npm run e2e:ci'
        working-directory: ${{ env.CLIENT_PATH }}

      - name: 'Build'
        run: 'echo "Skipping build. E2E already handles build."'
