name: Deploy Client

on:
  push:
    branches:
      - 'release/client'

env:
  CLIENT_PATH: 'src/client'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Setup Node'
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: 'Install packages'
        run: 'npm i'
        working-directory: ${{ env.CLIENT_PATH }}

      - name: 'Build'
        run: 'npm run build'
        working-directory: ${{ env.CLIENT_PATH }}

      - name: 'Deploy'
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ${{ env.CLIENT_PATH }}
